// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/home/jayce/Desktop/Projects/zhongyi-blog-admin/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/home/jayce/Desktop/Projects/zhongyi-blog-admin/node_modules/@ant-design/icons/es/icons/CrownOutlined';
export default { SmileOutlined, CrownOutlined };
