// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from '/home/jayce/Desktop/workspace/zhongyi-blog-admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@17.0.2_react@17.0.2/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import EditOutlined from '/home/jayce/Desktop/workspace/zhongyi-blog-admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@17.0.2_react@17.0.2/node_modules/@ant-design/icons/es/icons/EditOutlined';
import BlockOutlined from '/home/jayce/Desktop/workspace/zhongyi-blog-admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@17.0.2_react@17.0.2/node_modules/@ant-design/icons/es/icons/BlockOutlined';
import CrownOutlined from '/home/jayce/Desktop/workspace/zhongyi-blog-admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@17.0.2_react@17.0.2/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import SettingOutlined from '/home/jayce/Desktop/workspace/zhongyi-blog-admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@17.0.2_react@17.0.2/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { HomeOutlined, EditOutlined, BlockOutlined, CrownOutlined, SettingOutlined };
